// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdcOubTnifarUJwKyDjfPwer5V6gJ2zQ',
    appId: '1:923379348244:android:dd198879ce88ee56fe4801',
    messagingSenderId: '923379348244',
    projectId: 'delivery-app-92ed8',
    storageBucket: 'delivery-app-92ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCctNYj8lzTrzleFUpOibAj_R_jpuPApBE',
    appId: '1:923379348244:ios:7da9355a49357161fe4801',
    messagingSenderId: '923379348244',
    projectId: 'delivery-app-92ed8',
    storageBucket: 'delivery-app-92ed8.firebasestorage.app',
    iosBundleId: 'com.delivery.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9WzMEXREixxXEl9kBp8FK6ZRywpYC9tk',
    appId: '1:923379348244:web:ae8181ec459a7fadfe4801',
    messagingSenderId: '923379348244',
    projectId: 'delivery-app-92ed8',
    authDomain: 'delivery-app-92ed8.firebaseapp.com',
    storageBucket: 'delivery-app-92ed8.firebasestorage.app',
    measurementId: 'G-4YXWHWRD4T',
  );
}
